oit_ds_prefect_tools/object_storage.py

Create unique known hosts files for each task run to avoid rare conflicts where one task run tries to access the file while another is writing it

Known hosts fix

---

README.md
ucb_prefect_tools/util.py

So, I investigated the idea of auto-deploying the main branch of flow repos, but it seemed like more work/complexity than value, especially considering how easy it is to deploy flows from the command line. So instead I have added some main branch protections to prevent someone from accidentally deploying a main branch flow when they aren't an exact match with what's in Github. Let me know what you think of this approach!
I also did some reorganizing for clarity and removed the addition of flow retries, which don't work with our Prefect configuration (I'll add task retries in another PR).

DS-567 #comment Added main branch protections

---

ucb_prefect_tools/object_storage.py

This change makes the minio_list and s3_list task implementations behave the same as other list implementations in this module

Change object storage list tasks to return names not paths

---

ucb_prefect_tools/util.py

Relevant issue in the prefect repo: https://github.com/PrefectHQ/prefect/issues/8710
Due to a change in a recent version of s3fs (2023.3.0), prefect fails to find the source code for a flow unless the path argument has a trailing slash. Our ucb_prefect_tools package has this as a dependency.
Without this argument set, if you deploy using the most recent version you'll encounter an error like the following:
```
Flow could not be retrieved from deployment.
Traceback (most recent call last):
File "<frozen importlib._bootstrap_external>", line 846, in exec_module
File "<frozen importlib._bootstrap_external>", line 982, in get_code
File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'classroom_capture_users_report.py' …
```

UCBDE-189 Add path as an argument to Deployment.build_from_flow()

---

ucb_prefect_tools/comparer.py
ucb_prefect_tools/tests/test_comparer.py

Unit tests focus on low-level functions, since high-level functions are pretty basic wrappers of these. I did test the high-level functions as well.
The intent here is that by returning information in dicts, it can be easily adapted to other formats (like thrown into a DataFrame or pretty-printed or whatever). So while you can use this module in your own manual testing and validation, we could also easily integrate it with our next-gen cacheing system that we have planned: https://cu-oda.atlassian.net/browse/UCBDE-63?search_id=23f1d8af-8177-4ccd-89a8-6433d7a915ce
This is why I added this to the ucb_prefect_tools library, even though it doesn't directly relate to it right now. This paves the way for us to automatically generate diff reports whenever we cache a dataframe.
My approach to …

Add comparer and associated unit tests

---

ucb_prefect_tools/util.py

Prefect changed a few things sneakily between 2.8 and 2.10. This update to our tools package addresses both the issues I found in my audit.
1: prefect.utilities.filesystem.set_default_ignore_file has had its name changed to create_default_ignore_file
2: prefect.client.get_client has been relocated to prefect.client.orchestration.get_client

Fixes for upgrade to Prefect 2.10

---

ucb_prefect_tools/database.py
ucb_prefect_tools/object_storage.py
ucb_prefect_tools/rest.py

Added task retries to all idempotent tasks, with a delay of 10 minutes, trying 3 additional times (so up 30 minutes after initial attempt). My reasoning for having such long delays between retries is that we really want connection issues to resolve with retries, and a typical outage of an external system would hopefully resolve in 30 minutes tops. I don't want to retry every minute or so because it seems good to keep retries to a minimum while also maximizing the chances of a successful execution. Let me know what you think of this strategy!
Left retries off of rest.delete_many because presumably if this fails it could delete some and not others and then all subsequent attempts would also fail by definition in attempting to delete what was already deleted, so retrying doesn't seem like a …

UCBDE-64 Add task-level retries

---

ucb_prefect_tools/util.py

I tested this on a basic flow and it runs, but determining if this actually resolves the docker errors is hard because they are intermittent and based on multiple flows/tasks being started simultaneously. So I was thinking let's just deploy this harmless change and see if it helps!
Once I merge this, I will also update the default image to point to the new Prefect Tools release which will be v1.1.1

Add docker error workaround

---

ucb_prefect_tools/object_storage.py

`object_storage.put` has the ability to create the corresponding target directory for a filepath if the directory doesn't already exist. However, in instances where `put` is called asynchronously, the tasks will attempt to each create the necessary directory on their own, and some may fail with an `OSError`. This PR adds some code to handle instances where an OSError would be raised.
I've tested the package changes with a mock flow/fake data; an example log can be [found here.](https://app.prefect.cloud/account/86eb4016-3bda-40df-a926-a5da355f8393/workspace/5c4b372e-3f1b-4fed-a973-09381e72d9e2/flow-runs/flow-run/0d43e708-f186-4102-bd7e-0fdcdd29abef)
<details>
<summary>The flow code for this log can be viewed here.</summary>
<br>
Maybe not the most elegant example, but hopefully realistic …

UCBDE-245 address OSErrors when multiple put requests are occurring simultaneously

---

setup.cfg
ucb_prefect_tools/database.py

I ran into some hiccups with getting the new dsn for edb test and prod (which allows for failing over from COMP to SPSC) to work with cx_Oracle, so I figured I'd jump the gun and move us to the much neater, and M1-compatible, oracledb package. Turns out this is a simple change: I tested all the oracle features in the database package and I think we're good to go here.

UCBDE-93 Upgrade to oracledb

---

setup.cfg
ucb_prefect_tools/database.py

This is required for connecting to CIW, presumably due to this issue: https://github.com/oracle/python-oracledb/discussions/170
I tested this with CIW and it works now. Also tested functionality with EDB and it still works.

Use thick oracle client

---

README.md
setup.cfg
ucb_prefect_tools/util.py

These are the changes necessary to get our flows to run on OpenShift. Going forward, all flows will require a `:size:` label in their docstring of either "small" or "large" to determine how much resources the KubernetesJob will take up (see util._get_flow_infrastructure for specific limits). Most flows will be small, but some will need to be run as large. The Prefect open-shift work pool is set up to allow 1 large flow at a time and 4 small ones (with dev and main using separate OpenShift namespaces and separate resource pools).
Once you upgrade to this version of prefect tools, you won't be able to deploy to the Prefect VM anymore, but you can always re-install version 2.1.0 if you need to do so.
This PR also includes some quality of life improvements, like giving you the link to the …

UCBDE-58 Use KubernetesAgent for deployments

---

setup.cfg
ucb_prefect_tools/util.py

This will allow us to use username/password authentication for smtp which is necessary to send emails from openshift.
To deploy, we should update the smtp-connection block to use `"host": "smtp-ucb.colorado.edu", "port": 587` and the oit-ds-prefect user/password. This should work in all execution environments.

Add authentication to send_email

---

setup.cfg
ucb_prefect_tools/util.py

Incorporating optional additional tags in a flow's docstring allows us to address both https://cu-oda.atlassian.net/browse/UCBDE-280 and https://cu-oda.atlassian.net/browse/UCBDE-277. Crucially, this allows us to preserve the crm-ops and lms-leads tags which are necessary to trigger automated failure emails. See this for example usage: https://github.com/UCBoulder/oit-ds-flows-ata/blob/e57758bd262bf62a7496dc04d96f011724e91ae9/flows/canvas_data_monitor.py#L55

UCBDE-277,280 Add support for tags in flow docstring

---

setup.cfg
ucb_prefect_tools/rest.py

Adds the ability to set a custom timeout argument for rest.get and get_many. Default is 60.

Add timeout parameter to rest.get/get_many

---

setup.cfg
ucb_prefect_tools/util.py

In order for flow retries to work correctly, we need to configure a remote storage location for cached results. We can use MinIO for this: I created a "results" subfolder within the oit-ds-flow-storage bucket and set a Lifecycle policy to automatically clear objects out of there every 24 hours (since it's only used for temporary storage). In order to make this work with Prefect, we need to set the result_storage attribute for every Prefect flow. To facilitate this, I created a `deployable` decorator that we can plop on top of all our `flow` decorators within flow files to apply defaults (like MinIO result storage) to all our flows. That way if we ever want to modify the result storage or the flow timeouts, we can do this from a single location (the util module in this package). Individual …

Add remote result storage

---

setup.cfg
ucb_prefect_tools/object_storage.py

This adds support for OneDrive to the object_storage module. 
You can see an example of what a OneDrive storage block looks like here: https://app.prefect.cloud/account/86eb4016-3bda-40df-a926-a5da355f8393/workspace/5c4b372e-3f1b-4fed-a973-09381e72d9e2/blocks/block/39c0c85a-6db9-4f79-978b-8c4d03fd845c
You can see the results of a test flow here: https://app.prefect.cloud/account/86eb4016-3bda-40df-a926-a5da355f8393/workspace/5c4b372e-3f1b-4fed-a973-09381e72d9e2/flow-runs/flow-run/eadd7e38-1700-45a0-a462-4d7af237662c
Deployment steps:
Note: we'll worry about actually updating the math placement flow to use object_storage instead of rest in a future ticket.

UCBDE-55 Add OneDrive support to object_storage module

---

setup.cfg
ucb_prefect_tools/database.py

We've been seeing issues with inserting numerical or date-like values into Oracle databases in which, for some unknown reason, Oracle expects these values to be in a string format. This fixes that issue by converting all types to strings, and has been tested with several flows.

Fix issues with inserting or updating Oracle values

---

setup.cfg
ucb_prefect_tools/database.py

For the most part, Snowflake connections function just like other databases that Python connects to. But the usual way of using INSERT to add data to a table is not cost effective: instead you have to upload a CSV file to the table's "stage" and then use COPY INTO to fill the data into the table. As such, this adds a custom snowflake_insert implementation for that task and otherwise relies on the generic implementations. The only other thing is that UPDATE has the same limitations, but given that we rarely use this task and so far only for tiny changes, I just added a limit to the number of allowed updates to avoid potential runaway usage. If we find we need to do big updates in the future (unlikely), we can revisit this implementation.
Finally, I made some tweaks like applying the _cast …

UCBDE-662 Add support for Snowflake databases

---

setup.cfg
ucb_prefect_tools/data_archive.py

Allows using init to create an archive when no archive at that path exists. 
Catches a FileNotFoundError on the get_data attempt and passes an empty dataframe to the rest of the function.

Fix init on nonexistent archive

---

setup.cfg
ucb_prefect_tools/util.py

This PR, once installed/deployed, will cause all deployments to use a Kubernetes Work Pool running on OpenShift instead of a Docker Agent running on our Linux VM. It will also switch us from using MinIO for flow storage to using Github instead. It still uses MinIO for result storage.
Impacts:
- When you deploy or run a flow from the command line using this release, your Github working tree must be clean, meaning all changes committed and pushed. And then the deployment will use the code from Github to run the flow.
- This means you only need to deploy a flow once, and then subsequent pushes to Github will automatically update the deployment without the need to redeploy.
- If you use the run command, it will still delete the deployment when finished for the sake of convenience. Redeploying …

Switch to worker-based deployments on OpenShift

---

ucb_prefect_tools/database.py

Adds the ability to place a clause after insert statements, primarily for automatic conflict resolution.
Tested on a subset of sql inserts for our most common flavors.

add append_clause argument for inserts

---

ucb_prefect_tools/util.py

This PR makes it easier to invoke the parse_docstring_fields function in outside flows and scripts so that we can consistently parse docstrings the same way in other places (such as the oit-ds-flows-monitoring repo). No actual impact to the functionality of deployments. I tested this as part of my PR for the oit-ds-flows-monitoring repo, although this can be deployed independently.
Deploy steps:

Refactor parse_docstring_fields to take a string

---

setup.cfg
ucb_prefect_tools/util.py

This PR adds support for a new `:infra:` field to flow docstrings. The infra field lets you specify what type of work pool the flow should run on. If you are on the main git branch and your docstring has `:infra: k8s` then the flow will be deployed to the `k8s-main` work pool. On any other git branch it will be deployed to the `k8s-dev` work pool. This allows us to have some flows running on OpenShift and others running on a VM or another system based on resource usage.
Before this change the `--label` command-line option was already getting confusing, and the addition of this change just makes things worse. So I also replaced this cl option with a new one: `--work-pool`. This lets you directly override the work pool that you want the flow to be deployed to.
I also added protection so …

Add support for infra docstring field
